import type {
  Idea, PriorityColumn, Theme, Container, RoadmapBar,
  Objective, KeyResult, Initiative, Milestone,
} from '../models'

export const PRIORITY_COLUMNS: PriorityColumn[] = [
  { id: 'pc1', name: 'Revenue Potential', type: 'benefit', weight: 3, sortOrder: 0 },
  { id: 'pc2', name: 'Customer Delight', type: 'benefit', weight: 2, sortOrder: 1 },
  { id: 'pc3', name: 'Strategic Value', type: 'benefit', weight: 2, sortOrder: 2 },
  { id: 'pc4', name: 'Effort', type: 'cost', weight: 2, sortOrder: 3 },
  { id: 'pc5', name: 'Risk', type: 'cost', weight: 1, sortOrder: 4 },
]

export const IDEAS: Idea[] = [
  {
    id: 'i1',
    title: 'AI-powered ticket summarization',
    description: 'Automatically summarize long ticket threads using LLMs to reduce agent ramp-up time.',
    status: 'backlog',
    requester: 'Sarah Kim',
    votes: 34,
    tags: ['AI', 'tickets'],
    scores: [
      { ideaId: 'i1', columnId: 'pc1', score: 5 },
      { ideaId: 'i1', columnId: 'pc2', score: 4 },
      { ideaId: 'i1', columnId: 'pc3', score: 5 },
      { ideaId: 'i1', columnId: 'pc4', score: 3 },
      { ideaId: 'i1', columnId: 'pc5', score: 2 },
    ],
    createdAt: '2026-01-10T00:00:00Z',
    updatedAt: '2026-01-10T00:00:00Z',
  },
  {
    id: 'i2',
    title: 'Customer health score dashboard',
    description: 'A unified view of customer health signals: ticket volume, NPS, response time, churn risk.',
    status: 'planned',
    requester: 'Marcus Lee',
    votes: 28,
    tags: ['customers', 'analytics'],
    linkedBarId: 'bar2',
    scores: [
      { ideaId: 'i2', columnId: 'pc1', score: 4 },
      { ideaId: 'i2', columnId: 'pc2', score: 5 },
      { ideaId: 'i2', columnId: 'pc3', score: 4 },
      { ideaId: 'i2', columnId: 'pc4', score: 2 },
      { ideaId: 'i2', columnId: 'pc5', score: 1 },
    ],
    createdAt: '2026-01-15T00:00:00Z',
    updatedAt: '2026-01-20T00:00:00Z',
  },
  {
    id: 'i3',
    title: 'Two-way Slack integration',
    description: 'Allow agents to reply to tickets directly from Slack and receive real-time notifications.',
    status: 'in_progress',
    requester: 'Priya Patel',
    votes: 51,
    tags: ['integrations', 'slack'],
    linkedBarId: 'bar3',
    scores: [
      { ideaId: 'i3', columnId: 'pc1', score: 4 },
      { ideaId: 'i3', columnId: 'pc2', score: 5 },
      { ideaId: 'i3', columnId: 'pc3', score: 3 },
      { ideaId: 'i3', columnId: 'pc4', score: 3 },
      { ideaId: 'i3', columnId: 'pc5', score: 2 },
    ],
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-02-10T00:00:00Z',
  },
  {
    id: 'i4',
    title: 'Bulk ticket actions',
    description: 'Select multiple tickets and apply status changes, assignments, or tags in bulk.',
    status: 'backlog',
    requester: 'Tom Rivera',
    votes: 19,
    tags: ['tickets', 'productivity'],
    scores: [
      { ideaId: 'i4', columnId: 'pc1', score: 2 },
      { ideaId: 'i4', columnId: 'pc2', score: 3 },
      { ideaId: 'i4', columnId: 'pc3', score: 2 },
      { ideaId: 'i4', columnId: 'pc4', score: 2 },
      { ideaId: 'i4', columnId: 'pc5', score: 1 },
    ],
    createdAt: '2026-02-05T00:00:00Z',
    updatedAt: '2026-02-05T00:00:00Z',
  },
  {
    id: 'i5',
    title: 'SLA breach email alerts',
    description: 'Send configurable email/SMS alerts when a ticket is approaching SLA breach.',
    status: 'done',
    requester: 'Dana Wu',
    votes: 42,
    tags: ['SLA', 'notifications'],
    linkedBarId: 'bar5',
    scores: [
      { ideaId: 'i5', columnId: 'pc1', score: 3 },
      { ideaId: 'i5', columnId: 'pc2', score: 4 },
      { ideaId: 'i5', columnId: 'pc3', score: 3 },
      { ideaId: 'i5', columnId: 'pc4', score: 2 },
      { ideaId: 'i5', columnId: 'pc5', score: 1 },
    ],
    createdAt: '2025-11-01T00:00:00Z',
    updatedAt: '2026-01-05T00:00:00Z',
  },
]

export const THEMES: Theme[] = [
  { id: 't1', name: 'Core Platform', color: '#6366f1', sortOrder: 0 },
  { id: 't2', name: 'Customer Intelligence', color: '#10b981', sortOrder: 1 },
  { id: 't3', name: 'Integrations', color: '#f59e0b', sortOrder: 2 },
]

export const CONTAINERS: Container[] = [
  { id: 'c1', themeId: 't1', name: 'Ticket Management', color: '#818cf8', sortOrder: 0 },
  { id: 'c2', themeId: 't1', name: 'Agent Productivity', color: '#a5b4fc', sortOrder: 1 },
  { id: 'c3', themeId: 't2', name: 'Analytics & Reporting', color: '#34d399', sortOrder: 0 },
  { id: 'c4', themeId: 't3', name: 'Third-party Integrations', color: '#fbbf24', sortOrder: 0 },
]

export const ROADMAP_BARS: RoadmapBar[] = [
  {
    id: 'bar1',
    containerId: 'c1',
    themeId: 't1',
    title: 'AI Ticket Summarization',
    description: 'LLM-powered thread summaries for agents.',
    startDate: '2026-07-01',
    endDate: '2026-08-31',
    color: '#6366f1',
    percentComplete: 0,
    tags: ['AI', 'tickets'],
    isParked: false,
    linkedObjectiveIds: ['obj1'],
    createdAt: '2026-06-01T00:00:00Z',
  },
  {
    id: 'bar2',
    containerId: 'c3',
    themeId: 't2',
    title: 'Customer Health Dashboard',
    description: 'Unified health score view per customer.',
    startDate: '2026-07-15',
    endDate: '2026-09-30',
    color: '#10b981',
    percentComplete: 15,
    tags: ['customers', 'analytics'],
    isParked: false,
    linkedObjectiveIds: ['obj2'],
    createdAt: '2026-06-01T00:00:00Z',
  },
  {
    id: 'bar3',
    containerId: 'c4',
    themeId: 't3',
    title: 'Slack Two-Way Integration',
    description: 'Reply to tickets from Slack.',
    startDate: '2026-06-01',
    endDate: '2026-07-31',
    color: '#f59e0b',
    percentComplete: 60,
    tags: ['integrations', 'slack'],
    isParked: false,
    linkedObjectiveIds: ['obj1'],
    createdAt: '2026-05-01T00:00:00Z',
  },
  {
    id: 'bar4',
    containerId: 'c2',
    themeId: 't1',
    title: 'Bulk Ticket Actions',
    description: 'Multi-select + bulk apply status/tags.',
    startDate: '2026-09-01',
    endDate: '2026-09-30',
    color: '#8b5cf6',
    percentComplete: 0,
    tags: ['tickets', 'productivity'],
    isParked: false,
    linkedObjectiveIds: [],
    createdAt: '2026-06-01T00:00:00Z',
  },
  {
    id: 'bar5',
    containerId: 'c1',
    themeId: 't1',
    title: 'SLA Breach Alerts',
    description: 'Email/SMS alerts approaching breach.',
    startDate: '2026-04-01',
    endDate: '2026-05-31',
    color: '#ef4444',
    percentComplete: 100,
    tags: ['SLA'],
    isParked: false,
    linkedObjectiveIds: ['obj2'],
    createdAt: '2026-03-01T00:00:00Z',
  },
  {
    id: 'bar6',
    themeId: undefined,
    title: 'Mobile App Push Notifications',
    description: 'Native push for iOS and Android agents.',
    startDate: '2026-10-01',
    endDate: '2026-11-30',
    color: '#ec4899',
    percentComplete: 0,
    tags: ['mobile'],
    isParked: true,
    linkedObjectiveIds: [],
    createdAt: '2026-06-01T00:00:00Z',
  },
]

export const MILESTONES: Milestone[] = [
  { id: 'm1', title: 'Q3 Launch', date: '2026-09-30', color: '#6366f1' },
  { id: 'm2', title: 'Beta Release', date: '2026-08-01', color: '#10b981' },
]

export const KEY_RESULTS: KeyResult[] = [
  { id: 'kr1', objectiveId: 'obj1', title: 'Reduce avg handle time', unit: 'percent', targetValue: 20, currentValue: 8, sortOrder: 0 },
  { id: 'kr2', objectiveId: 'obj1', title: 'AI feature adoption rate', unit: 'percent', targetValue: 60, currentValue: 22, sortOrder: 1 },
  { id: 'kr3', objectiveId: 'obj2', title: 'NPS improvement', unit: 'number', targetValue: 15, currentValue: 6, sortOrder: 0 },
  { id: 'kr4', objectiveId: 'obj2', title: 'Churn reduction revenue saved', unit: 'dollar', targetValue: 500000, currentValue: 120000, sortOrder: 1 },
  { id: 'kr5', objectiveId: 'obj3', title: 'New integrations shipped', unit: 'number', targetValue: 5, currentValue: 2, sortOrder: 0 },
  { id: 'kr6', objectiveId: 'obj3', title: 'Integration-sourced revenue', unit: 'dollar', targetValue: 200000, currentValue: 45000, sortOrder: 1 },
]

export const OBJECTIVES: Objective[] = [
  {
    id: 'obj1',
    title: 'Accelerate agent productivity with AI',
    description: 'Leverage AI to reduce manual work and improve resolution speed.',
    color: '#6366f1',
    scope: 'company',
    ragStatus: 'amber',
    teamName: 'Platform Team',
    keyResults: KEY_RESULTS.filter(kr => kr.objectiveId === 'obj1'),
    linkedBarIds: ['bar1', 'bar3'],
    linkedInitiativeIds: ['init1'],
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'obj2',
    title: 'Improve customer retention and health visibility',
    description: 'Give CSMs the data they need to intervene before churn.',
    color: '#10b981',
    scope: 'team',
    ragStatus: 'green',
    teamName: 'Customer Success Tools',
    keyResults: KEY_RESULTS.filter(kr => kr.objectiveId === 'obj2'),
    linkedBarIds: ['bar2', 'bar5'],
    linkedInitiativeIds: ['init2'],
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'obj3',
    title: 'Expand ecosystem through integrations',
    description: 'Build out the integration marketplace to reduce churn from tool-switching.',
    color: '#f59e0b',
    scope: 'team',
    ragStatus: 'red',
    teamName: 'Integrations Team',
    keyResults: KEY_RESULTS.filter(kr => kr.objectiveId === 'obj3'),
    linkedBarIds: ['bar3'],
    linkedInitiativeIds: ['init3'],
    createdAt: '2026-01-01T00:00:00Z',
  },
]

export const INITIATIVES: Initiative[] = [
  {
    id: 'init1',
    title: 'AI-First Agent Experience',
    description: 'Redesign the agent workflow with AI assistance at every step — summarization, suggested replies, smart routing.',
    businessValue: 'Estimated 25% reduction in handle time; key differentiator for enterprise deals.',
    status: 'in_progress',
    objectiveId: 'obj1',
    createdAt: '2026-01-15T00:00:00Z',
  },
  {
    id: 'init2',
    title: 'Customer 360 Platform',
    description: 'Centralized view of every customer signal — tickets, NPS, contracts, health score — in one dashboard.',
    businessValue: 'Enables proactive retention; targeted at reducing churn by 10%.',
    status: 'in_progress',
    objectiveId: 'obj2',
    createdAt: '2026-02-01T00:00:00Z',
  },
  {
    id: 'init3',
    title: 'Integration Marketplace v2',
    description: 'Self-serve integration builder + curated marketplace with Slack, Salesforce, Zendesk, and HubSpot.',
    businessValue: 'Opens new GTM channel; reduces churn from competitive displacement.',
    status: 'draft',
    objectiveId: 'obj3',
    createdAt: '2026-03-01T00:00:00Z',
  },
]
